# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./backend/.env:/app/.env
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/legalai
      - VECTOR_DB_HOST=vector-db
      - VECTOR_DB_PORT=19530
    depends_on:
      - db
      - vector-db
    networks:
      - legalai-network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - legalai-network

  vector-db:
    build:
      context: .
      dockerfile: docker/vector-db.Dockerfile
    ports:
      - "19530:19530"
      - "19121:19121"
    volumes:
      - milvus_data:/var/lib/milvus
    environment:
      - MILVUS_HOST=vector-db
      - MILVUS_PORT=19530
    networks:
      - legalai-network

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=legalai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - legalai-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db
    networks:
      - legalai-network

volumes:
  postgres_data:
  milvus_data:

networks:
  legalai-network:
    driver: bridge